# Generated by Django 3.1.2 on 2024-05-31 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('BT', 'বটতলা'), ('PG', 'প্রান্তিক গেইট'), ('DD', 'ডিপার্টমেন্টের দোকান'), ('MR', 'অন্যান্য')], max_length=50)),
                ('area', models.CharField(choices=[('1', 'সাভার'), ('2', 'প্রান্তিক গেইট '), ('3', 'সকল মহিলা হল'), ('4', 'ডেইরি গেইট'), ('5', 'সামাজিক বিজ্ঞান অনুষদ, গণিত ও পরিসংখ্যান বিভাগ, নতুন কলা ভবন, পদার্থবিজ্ঞান বিভাগ, রসায়ন বিভাগ'), ('6', 'পুরাতন কলা ভবন, ব্যবসায় শিক্ষা অনুষদ, আল বেরুনি হল'), ('7', 'ভূতত্ত্ব, সি.এস.ই ও পরিবেশ বিজ্ঞান ভবন, বটতলা, বঙ্গবন্ধু হল, আ.ফ.ম  কামালউদ্দিন হল, সালাম বরকত হল'), ('8', 'মওলানা ভাসানী হল, বিশ্বকবি রবীন্দ্রনাথ ঠাকুর হল, রফিক জব্বার হল'), ('9', 'জীববিজ্ঞান অনুষদ'), ('10', 'মীর মশাররফ হোসেন হল')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('VV', 'ভাত-তরকারি'), ('SF', 'স্ট্রিট ফুড'), ('FF', 'ফাস্টফুড'), ('TF', 'টং এর দোকান'), ('OF', 'অন্যান্য')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_non_veg', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('image', models.ImageField(default='media/default_item.png', upload_to='item_pics', verbose_name='Feature Image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='items.shop')),
            ],
        ),
    ]
